application: rssengine
version: 1
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /queue/.*
  script: handlers/queue.py
  login: admin

- url: /cron/.*
  script: handlers/cron.py
  login: admin

- url: /.*
  script: rssengine.py