application: rssengine
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

admin_console:
  pages:
  - name: Accounts Pending Approval
    url: /admin/pending

handlers:

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /queue/.*
  script: rssengine.py
  login: admin

- url: /cron/.*
  script: rssengine.py
  login: admin

- url: /.*
  script: rssengine.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?LICENSE
- ^(.*/)?.*.md$